apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod
#namePrefix: prod-

# Image with the name SKILLSETS_API_IMAGE_NAME should have its image name 
# changed to codesenju/skillsets-api and its tag changed
images:
- name: SKILLSETS_API_IMAGE_NAME
  newName: codesenju/skillsets-api
  newTag: latest

# Generate a configmap
configMapGenerator:
- literals:
  - REDIS_HOST=localhost
  - REDIS_PORT="6379"
  - PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
  - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT='http://my-collector-xray-collector.opentelemetry-operator-system.svc.cluster.local:4317'
  - OTEL_PROPAGATORS=xray
  - OTEL_PYTHON_ID_GENERATOR=xray
  - OTEL_RESOURCE_ATTRIBUTES='service.name=skillsets-api'
  name: skillsets-config

# Takes the name of the redis service and uses it as the value for the REDIS_HOST key in the skillsets-config ConfigMap.
replacements:
- source:
    fieldPath: metadata.name
    kind: Service
    name: redis-test
#    name: skillsets-redis-db
    version: v1
  targets:
  - fieldPaths:
    - data.REDIS_HOST
    select:
      kind: ConfigMap
      name: skillsets-config
  - fieldPaths:
    -  spec.scaleTargetRef.name
    select:
      kind: HorizontalPodAutoscaler
      name: skillsets-redis-db-hpa
- source:
    fieldPath: metadata.name
    kind: Service
    name: skillsets
    version: v1
  targets:
  - fieldPaths:
    -  spec.scaleTargetRef.name
    select:
      kind: HorizontalPodAutoscaler
      name: skillsets-api-hpa
#############
## PATCHES ##
#############
# This specifies that the patch in ingress-patch.yaml 
# should be applied to an Ingress resource named skillsets-ingress 
# in the networking.k8s.io/v1 API group and version. 
patches:
- path: ingress_patch.yaml
  target:
    group: networking.k8s.io
    kind: Ingress
    name: skillsets-ingress
    version: v1
#- patch: |-
#    - op: replace # action 
#      path: /spec/rules/0/host # resource we want to change
#      value: prod-skillsets-ui.lmasu.co.za # value we want to use for patching 
#  target:
#    group: networking.k8s.io
#    version: v1
#    kind: Ingress
#    name: skillsets-ui-ingress
- path: topology_spread_patch.yaml
- path: mem_cpu_patch.yaml
- path: health_check_patch.yaml
- path: sts_topology_spread.yaml
- path: redis_test_tsc.yaml
#- path: instrumentation_patch.yaml
#- path: replica_count_patch.yaml

resources:
- ../base/