################
## DEPLOYMENT ##
################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  skillsets-api
spec:
  template:
    spec:
      containers:
      - name:  skillsets-api
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 115m
            memory: 115Mi