################
## DEPLOYMENT ##
################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  skillsets
spec:
  template:
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: skillsets
#      - maxSkew: 1
#        topologyKey: kubernetes.io/hostname
#        whenUnsatisfiable: DoNotSchedule
#        labelSelector:
#          matchLabels:
#            app: skillsets